### ISSUE TITLE
Generator not working with an error while reading SAP-icons-TNT.json file

### ISSUE THREAD

**Issue by kurumesa** [geert-janklaps/generator-btp-diagram-icons#2]
`Cannot find module 'C:\Users\sandesh\AppData\Roaming\npm\node_modules\generator-btp-diagram-icons\node_modules\@ui5\webcomponents-icons-tnt\dist\generated\assets\SAP-icons-TNT.json'`

I get this error while generating

**Comment by jastill** [comment]
Looks like ui5-webcomponents now added versions to the icon paths. 

This affects both tnticons and businesssuiteicons .
